name: Release New Version
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src/main/resources/fabric.mod.json
          field: version
          value: ${{ github.ref_name }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename File
        run: |
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug.jar ${{ github.workspace }}/Quill-Notifications-${{ github.ref_name }}.jar; 
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug-javadoc.jar ${{ github.workspace }}/Quill-Notifications-${{ github.ref_name }}-javadoc.jar;
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug-sources.jar ${{ github.workspace }}/Quill-Notifications-${{ github.ref_name }}-sources.jar;

      - name: Publish Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            ${{ github.workspace }}/Quill-Notifications-${{ github.ref_name }}.jar
            ${{ github.workspace }}/Quill-Notifications-${{ github.ref_name }}-javadoc.jar
            ${{ github.workspace }}/Quill-Notifications-{{ github.ref_name }}-sources.jar
            java: 17
          java: 17