name: Release New Version
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Set Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src/main/resources/fabric.mod.json
          field: version
          value: ${{ github.event.release.tag_name }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename File
        run: |
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug.jar ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}.jar; 
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug-javadoc.jar ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}-javadoc.jar;
          mv ${{ github.workspace }}/build/libs/Quill-Notifications-debug-sources.jar ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}-sources.jar;

      - name: Publish Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}.jar
            ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}-javadoc.jar
            ${{ github.workspace }}/Quill-Notifications-${{ github.event.release.tag_name }}-sources.jar
            java: 21
          java: 21
          game-versions: |
            1.20.6
            1.20.5
            1.20.4
            1.20.3
            1.20.2
            1.20.1
            1.20
            1.19.4
            1.19.3
            1.19.2
            1.19.1
            1.19
            1.18.2
            1.18.1
            1.18
            1.17.1
            1.17
            1.16.5
